name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Triển khai khi có commit vào nhánh main

jobs:
  build:
    runs-on: ubuntu-latest  # Chạy trên môi trường Ubuntu mới nhất

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Lấy mã nguồn từ repository

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: |
        docker build -t 312001loi/yolov10onnx_raspbian:latest .

    - name: Push Docker image
      run: |
        docker push 312001loi/yolov10onnx_raspbian:latest
